#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraMode_Grape_Bramble_Shield

#include "Basic.hpp"

#include "Athena_PlayerCameraModeBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Athena_PlayerCameraMode_Grape_Bramble_Shield.Athena_PlayerCameraMode_Grape_Bramble_Shield_C
// 0x0000 (0x0DC0 - 0x0DC0)
class UAthena_PlayerCameraMode_Grape_Bramble_Shield_C final : public UAthena_PlayerCameraModeBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_PlayerCameraMode_Grape_Bramble_Shield_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_PlayerCameraMode_Grape_Bramble_Shield_C")
	}
	static class UAthena_PlayerCameraMode_Grape_Bramble_Shield_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraMode_Grape_Bramble_Shield_C>();
	}
};
DUMPER7_ASSERTS_UAthena_PlayerCameraMode_Grape_Bramble_Shield_C;

SDK_NAMESPACE_END
