#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaTemperature

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass AthenaTemperature.AthenaTemperature_C
// 0x0008 (0x02A0 - 0x0298)
class UAthenaTemperature_C final : public UAthenaTemperatureBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_AthenaTemperature(int32 EntryPoint);
	void Construct();
	void ShowTemperatureChanged(bool bShowTemperature);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaTemperature_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaTemperature_C")
	}
	static class UAthenaTemperature_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaTemperature_C>();
	}
};
DUMPER7_ASSERTS_UAthenaTemperature_C;

SDK_NAMESPACE_END
