#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_CameraLens_Cube_Area

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function B_CameraLens_Cube_Area.B_CameraLens_Cube_Area_C.ExecuteUbergraph_B_CameraLens_Cube_Area
// 0x0004 (0x0004 - 0x0000)
struct B_CameraLens_Cube_Area_C_ExecuteUbergraph_B_CameraLens_Cube_Area final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_B_CameraLens_Cube_Area_C_ExecuteUbergraph_B_CameraLens_Cube_Area;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
