#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BB_RadioNext

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BB_RadioNext.BB_RadioNext_C
// 0x0000 (0x00B0 - 0x00B0)
class UBB_RadioNext_C final : public UFortMobileActionButtonBehavior
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BB_RadioNext_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BB_RadioNext_C")
	}
	static class UBB_RadioNext_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBB_RadioNext_C>();
	}
};
DUMPER7_ASSERTS_UBB_RadioNext_C;

SDK_NAMESPACE_END
