#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_HitImpact_ShoppingCart

#include "Basic.hpp"

#include "CameraShake_HitImpact_Vehicle_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CameraShake_HitImpact_ShoppingCart.CameraShake_HitImpact_ShoppingCart_C
// 0x0000 (0x0160 - 0x0160)
class UCameraShake_HitImpact_ShoppingCart_C final : public UCameraShake_HitImpact_Vehicle_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShake_HitImpact_ShoppingCart_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShake_HitImpact_ShoppingCart_C")
	}
	static class UCameraShake_HitImpact_ShoppingCart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_HitImpact_ShoppingCart_C>();
	}
};
DUMPER7_ASSERTS_UCameraShake_HitImpact_ShoppingCart_C;

SDK_NAMESPACE_END
