#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ControllerActionsMenuEntry

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass ControllerActionsMenuEntry.ControllerActionsMenuEntry_C
// 0x0000 (0x0BA8 - 0x0BA8)
class UControllerActionsMenuEntry_C final : public UFortControllerActionsMenuEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ControllerActionsMenuEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ControllerActionsMenuEntry_C")
	}
	static class UControllerActionsMenuEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UControllerActionsMenuEntry_C>();
	}
};
DUMPER7_ASSERTS_UControllerActionsMenuEntry_C;

SDK_NAMESPACE_END
