#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Creative_Background_Widget

#include "Basic.hpp"

#include "UMG_classes.hpp"
#include "Slate_structs.hpp"
#include "EBillboardshadowDirection_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass Creative_Background_Widget.Creative_Background_Widget_C
// 0x0010 (0x0270 - 0x0260)
class UCreative_Background_Widget_C final : public UUserWidget
{
public:
	class UBorder*                                Border_0;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             UserText;                                          // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetText(const class FString& Text);
	void SetBackgroundColor(const struct FLinearColor& Color);
	void SetTextScale(int32 FontSize);
	void SetTextAlignment(ETextJustify Alignment);
	void SetTextColor(const struct FLinearColor& TextColor);
	void SetTextFont(int32 TextFont, int32 OutlineStrength);
	void SetShadow(EBillboardshadowDirection Shadow, float ShadowScale);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Creative_Background_Widget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Creative_Background_Widget_C")
	}
	static class UCreative_Background_Widget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCreative_Background_Widget_C>();
	}
};
DUMPER7_ASSERTS_UCreative_Background_Widget_C;

SDK_NAMESPACE_END
