#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DA_BoostJumpPack

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "CommonInput_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DA_BoostJumpPack.DA_BoostJumpPack_C
// 0x0068 (0x0DA8 - 0x0D40)
class ADA_BoostJumpPack_C final : public AFortCustomizableAbilityDecoTool
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTagContainer                  ErrorReason;                                       // 0x0D48(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  ErrorReasonGamepad;                                // 0x0D68(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FGameplayTagContainer                  ErrorCannotUse;                                    // 0x0D88(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_DA_BoostJumpPack(int32 EntryPoint);
	void BPPressTrigger(class AFortDecoHelper* FortDecoHelper);
	void RaiseUsageError(const struct FGameplayTagContainer& FailedReason);
	void IsOnGround(bool* bOnGround);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DA_BoostJumpPack_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DA_BoostJumpPack_C")
	}
	static class ADA_BoostJumpPack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADA_BoostJumpPack_C>();
	}
};
DUMPER7_ASSERTS_ADA_BoostJumpPack_C;

SDK_NAMESPACE_END
