#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_ActivePower_LeapGlider_Cancel_Parent

#include "Basic.hpp"

#include "GA_Athena_ActivePower_LeapGlider_Cancel_Parent_classes.hpp"
#include "GA_Athena_ActivePower_LeapGlider_Cancel_Parent_parameters.hpp"


SDK_NAMESPACE_START

// Function GA_Athena_ActivePower_LeapGlider_Cancel_Parent.GA_Athena_ActivePower_LeapGlider_Cancel_Parent_C.ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_Cancel_Parent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_ActivePower_LeapGlider_Cancel_Parent_C::ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_Cancel_Parent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_Cancel_Parent_C", "ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_Cancel_Parent");

	Params::GA_Athena_ActivePower_LeapGlider_Cancel_Parent_C_ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_Cancel_Parent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_ActivePower_LeapGlider_Cancel_Parent.GA_Athena_ActivePower_LeapGlider_Cancel_Parent_C.RanAbilitySuccesfully
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_Cancel_Parent_C::RanAbilitySuccesfully()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_Cancel_Parent_C", "RanAbilitySuccesfully");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_ActivePower_LeapGlider_Cancel_Parent.GA_Athena_ActivePower_LeapGlider_Cancel_Parent_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_Cancel_Parent_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_Cancel_Parent_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
