#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_BirthdayGiftBox

#include "Basic.hpp"

#include "GA_Athena_SuperTowerGrenadeWithTrajectory_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_Athena_BirthdayGiftBox.GA_Athena_BirthdayGiftBox_C
// 0x0000 (0x0EA8 - 0x0EA8)
class UGA_Athena_BirthdayGiftBox_C final : public UGA_Athena_SuperTowerGrenadeWithTrajectory_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Athena_BirthdayGiftBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Athena_BirthdayGiftBox_C")
	}
	static class UGA_Athena_BirthdayGiftBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_BirthdayGiftBox_C>();
	}
};
DUMPER7_ASSERTS_UGA_Athena_BirthdayGiftBox_C;

SDK_NAMESPACE_END
