#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent

#include "Basic.hpp"

#include "GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_classes.hpp"
#include "GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_parameters.hpp"


SDK_NAMESPACE_START

// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent");

	Params::GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C_ExecuteUbergraph_GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.CallRemove
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::CallRemove()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "CallRemove");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.PawnLanded
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::PawnLanded(const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "PawnLanded");

	Params::GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C_PawnLanded Parms{};

	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.SetUpBinds
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::SetUpBinds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "SetUpBinds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.SetUpWaits
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::SetUpWaits()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "SetUpWaits");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.Added_5E34F7544112B6D9154421AAB17CB5BA
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::Added_5E34F7544112B6D9154421AAB17CB5BA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "Added_5E34F7544112B6D9154421AAB17CB5BA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent.GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C.Added_5647B6024F8D299ABD8940AE9C5CE269
// (BlueprintCallable, BlueprintEvent)

void UGA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C::Added_5647B6024F8D299ABD8940AE9C5CE269()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Athena_ActivePower_LeapGlider_OnLandCooldown_Parent_C", "Added_5647B6024F8D299ABD8940AE9C5CE269");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
