#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HighTower_Date_BallLightning

#include "Basic.hpp"

#include "GA_HighTower_Date_BallLightning_classes.hpp"
#include "GA_HighTower_Date_BallLightning_parameters.hpp"


SDK_NAMESPACE_START

// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.ExecuteUbergraph_GA_HighTower_Date_BallLightning
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HighTower_Date_BallLightning_C::ExecuteUbergraph_GA_HighTower_Date_BallLightning(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "ExecuteUbergraph_GA_HighTower_Date_BallLightning");

	Params::GA_HighTower_Date_BallLightning_C_ExecuteUbergraph_GA_HighTower_Date_BallLightning Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.CustomEvent_2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortProjectileBase*              ProjectileSpawned                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HighTower_Date_BallLightning_C::CustomEvent_2(class AFortProjectileBase* ProjectileSpawned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "CustomEvent_2");

	Params::GA_HighTower_Date_BallLightning_C_CustomEvent_2 Parms{};

	Parms.ProjectileSpawned = ProjectileSpawned;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_HighTower_Date_BallLightning_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.CastMontageNotifyStart
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              NotifyTag                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UGA_HighTower_Date_BallLightning_C::CastMontageNotifyStart(const struct FGameplayTag& NotifyTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "CastMontageNotifyStart");

	Params::GA_HighTower_Date_BallLightning_C_CastMontageNotifyStart Parms{};

	Parms.NotifyTag = std::move(NotifyTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.MulticastThrow
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void UGA_HighTower_Date_BallLightning_C::MulticastThrow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "MulticastThrow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.CustomEvent_1
// (BlueprintCallable, BlueprintEvent)

void UGA_HighTower_Date_BallLightning_C::CustomEvent_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "CustomEvent_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGA_HighTower_Date_BallLightning_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "K2_OnEndAbility");

	Params::GA_HighTower_Date_BallLightning_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.Released
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   HoldTime                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HighTower_Date_BallLightning_C::Released(float HoldTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "Released");

	Params::GA_HighTower_Date_BallLightning_C_Released Parms{};

	Parms.HoldTime = HoldTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.OnSync_CD7C69E84CC97FE216AEA089D8A95231
// (BlueprintCallable, BlueprintEvent)

void UGA_HighTower_Date_BallLightning_C::OnSync_CD7C69E84CC97FE216AEA089D8A95231()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "OnSync_CD7C69E84CC97FE216AEA089D8A95231");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.Added_5CB6885747BB3160A88BD2880752E130
// (BlueprintCallable, BlueprintEvent)

void UGA_HighTower_Date_BallLightning_C::Added_5CB6885747BB3160A88BD2880752E130()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "Added_5CB6885747BB3160A88BD2880752E130");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.Added_60A0EC084FB8C048E3BA878CCFA25811
// (BlueprintCallable, BlueprintEvent)

void UGA_HighTower_Date_BallLightning_C::Added_60A0EC084FB8C048E3BA878CCFA25811()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "Added_60A0EC084FB8C048E3BA878CCFA25811");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.InitAbility
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_HighTower_Date_BallLightning_C::InitAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "InitAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.Check Min Hold Time
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// float*                                  MinTimeRemaining                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HighTower_Date_BallLightning_C::Check_Min_Hold_Time(bool* Success, float* MinTimeRemaining)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "Check Min Hold Time");

	Params::GA_HighTower_Date_BallLightning_C_Check_Min_Hold_Time Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Success != nullptr)
		*Success = Parms.Success;

	if (MinTimeRemaining != nullptr)
		*MinTimeRemaining = Parms.MinTimeRemaining;
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.PowerSpawnProjectile
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AFortProjectileBase**             ProjectileSpawned                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HighTower_Date_BallLightning_C::PowerSpawnProjectile(class AFortProjectileBase** ProjectileSpawned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "PowerSpawnProjectile");

	Params::GA_HighTower_Date_BallLightning_C_PowerSpawnProjectile Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ProjectileSpawned != nullptr)
		*ProjectileSpawned = Parms.ProjectileSpawned;
}


// Function GA_HighTower_Date_BallLightning.GA_HighTower_Date_BallLightning_C.K2_CanActivateAbility
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FGameplayAbilityActorInfo& ActorInfo                                              (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)
// const struct FGameplayAbilitySpecHandle&Handle                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTagContainer*           RelevantTags                                           (Parm, OutParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UGA_HighTower_Date_BallLightning_C::K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpecHandle& Handle, struct FGameplayTagContainer* RelevantTags) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Date_BallLightning_C", "K2_CanActivateAbility");

	Params::GA_HighTower_Date_BallLightning_C_K2_CanActivateAbility Parms{};

	Parms.ActorInfo = std::move(ActorInfo);
	Parms.Handle = std::move(Handle);

	UObject::ProcessEvent(Func, &Parms);

	if (RelevantTags != nullptr)
		*RelevantTags = std::move(Parms.RelevantTags);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
