#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_HighTower_Squash_WhirlwindBlast_Knockback

#include "Basic.hpp"

#include "GA_HighTower_Squash_WhirlwindBlast_Knockback_classes.hpp"
#include "GA_HighTower_Squash_WhirlwindBlast_Knockback_parameters.hpp"


SDK_NAMESPACE_START

// Function GA_HighTower_Squash_WhirlwindBlast_Knockback.GA_HighTower_Squash_WhirlwindBlast_Knockback_C.ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_Knockback
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_HighTower_Squash_WhirlwindBlast_Knockback_C::ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_Knockback(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Squash_WhirlwindBlast_Knockback_C", "ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_Knockback");

	Params::GA_HighTower_Squash_WhirlwindBlast_Knockback_C_ExecuteUbergraph_GA_HighTower_Squash_WhirlwindBlast_Knockback Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_HighTower_Squash_WhirlwindBlast_Knockback.GA_HighTower_Squash_WhirlwindBlast_Knockback_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_HighTower_Squash_WhirlwindBlast_Knockback_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_HighTower_Squash_WhirlwindBlast_Knockback_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
