#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Trap_FloorSpikes

#include "Basic.hpp"

#include "GA_TrapGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GA_Trap_FloorSpikes.GA_Trap_FloorSpikes_C
// 0x0000 (0x0968 - 0x0968)
class UGA_Trap_FloorSpikes_C final : public UGA_TrapGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_Trap_FloorSpikes_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_Trap_FloorSpikes_C")
	}
	static class UGA_Trap_FloorSpikes_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Trap_FloorSpikes_C>();
	}
};
DUMPER7_ASSERTS_UGA_Trap_FloorSpikes_C;

SDK_NAMESPACE_END
