#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Boombox_Boom

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_Boombox_Boom.GCN_Boombox_Boom_C
// 0x0000 (0x01A0 - 0x01A0)
class UGCN_Boombox_Boom_C final : public UFortGameplayCueNotify_Burst
{
public:
	void OnBurst(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Boombox_Boom_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Boombox_Boom_C")
	}
	static class UGCN_Boombox_Boom_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Boombox_Boom_C>();
	}
};
DUMPER7_ASSERTS_UGCN_Boombox_Boom_C;

SDK_NAMESPACE_END
