#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Deimos_Monster_Spawn

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCN_Deimos_Monster_Spawn.GCN_Deimos_Monster_Spawn_C
// 0x0008 (0x01A8 - 0x01A0)
class UGCN_Deimos_Monster_Spawn_C final : public UFortGameplayCueNotify_Burst
{
public:
	class USoundConcurrency*                      ConcurrencySettings;                               // 0x01A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void OnBurst(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UParticleSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCN_Deimos_Monster_Spawn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCN_Deimos_Monster_Spawn_C")
	}
	static class UGCN_Deimos_Monster_Spawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Deimos_Monster_Spawn_C>();
	}
};
DUMPER7_ASSERTS_UGCN_Deimos_Monster_Spawn_C;

SDK_NAMESPACE_END
