#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Lowgrav

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_Lowgrav.GE_Lowgrav_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Lowgrav_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Lowgrav_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Lowgrav_C")
	}
	static class UGE_Lowgrav_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Lowgrav_C>();
	}
};
DUMPER7_ASSERTS_UGE_Lowgrav_C;

SDK_NAMESPACE_END
