#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GET_DirectVehicleDamage

#include "Basic.hpp"

#include "Get_DirectDamageParent_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GET_DirectVehicleDamage.GET_DirectVehicleDamage_C
// 0x0000 (0x07B8 - 0x07B8)
class UGET_DirectVehicleDamage_C final : public UGet_DirectDamageParent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GET_DirectVehicleDamage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GET_DirectVehicleDamage_C")
	}
	static class UGET_DirectVehicleDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGET_DirectVehicleDamage_C>();
	}
};
DUMPER7_ASSERTS_UGET_DirectVehicleDamage_C;

SDK_NAMESPACE_END
