#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InvisibleCursorWidget

#include "Basic.hpp"

#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass InvisibleCursorWidget.InvisibleCursorWidget_C
// 0x0000 (0x0260 - 0x0260)
class UInvisibleCursorWidget_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("InvisibleCursorWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InvisibleCursorWidget_C")
	}
	static class UInvisibleCursorWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInvisibleCursorWidget_C>();
	}
};
DUMPER7_ASSERTS_UInvisibleCursorWidget_C;

SDK_NAMESPACE_END
