#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionGen_Creative_Hyena_Z

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MissionGen_Creative_Hyena_Z.MissionGen_Creative_Hyena_Z_C
// 0x0000 (0x06C0 - 0x06C0)
class UMissionGen_Creative_Hyena_Z_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MissionGen_Creative_Hyena_Z_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MissionGen_Creative_Hyena_Z_C")
	}
	static class UMissionGen_Creative_Hyena_Z_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_Creative_Hyena_Z_C>();
	}
};
DUMPER7_ASSERTS_UMissionGen_Creative_Hyena_Z_C;

SDK_NAMESPACE_END
