#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionInfoPanel

#include "Basic.hpp"

#include "MissionInfoPanel_classes.hpp"
#include "MissionInfoPanel_parameters.hpp"


SDK_NAMESPACE_START

// Function MissionInfoPanel.MissionInfoPanel_C.ExecuteUbergraph_MissionInfoPanel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMissionInfoPanel_C::ExecuteUbergraph_MissionInfoPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionInfoPanel_C", "ExecuteUbergraph_MissionInfoPanel");

	Params::MissionInfoPanel_C_ExecuteUbergraph_MissionInfoPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionInfoPanel.MissionInfoPanel_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UMissionInfoPanel_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionInfoPanel_C", "PreConstruct");

	Params::MissionInfoPanel_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MissionInfoPanel.MissionInfoPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMissionInfoPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionInfoPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MissionInfoPanel.MissionInfoPanel_C.SetMissionStyle
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FFortChallengeSetStyle&    Style                                                  (BlueprintVisible, BlueprintReadOnly, Parm)

void UMissionInfoPanel_C::SetMissionStyle(const struct FFortChallengeSetStyle& Style)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MissionInfoPanel_C", "SetMissionStyle");

	Params::MissionInfoPanel_C_SetMissionStyle Parms{};

	Parms.Style = std::move(Style);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
