#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBWA_M1_RoofS

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PBWA_M1_RoofS.PBWA_M1_RoofS_C
// 0x0000 (0x0B70 - 0x0B70)
class APBWA_M1_RoofS_C final : public ABuildingRoof
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PBWA_M1_RoofS_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PBWA_M1_RoofS_C")
	}
	static class APBWA_M1_RoofS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APBWA_M1_RoofS_C>();
	}
};
DUMPER7_ASSERTS_APBWA_M1_RoofS_C;

SDK_NAMESPACE_END
