#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scoreboard_UI

#include "Basic.hpp"

#include "Scoreboard_UI_classes.hpp"
#include "Scoreboard_UI_parameters.hpp"


SDK_NAMESPACE_START

// Function Scoreboard_UI.Scoreboard_UI_C.ExecuteUbergraph_Scoreboard_UI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScoreboard_UI_C::ExecuteUbergraph_Scoreboard_UI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "ExecuteUbergraph_Scoreboard_UI");

	Params::Scoreboard_UI_C_ExecuteUbergraph_Scoreboard_UI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Scoreboard_UI.Scoreboard_UI_C.HideMinigameEndUI
// (BlueprintCallable, BlueprintEvent)

void UScoreboard_UI_C::HideMinigameEndUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "HideMinigameEndUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Scoreboard_UI.Scoreboard_UI_C.ShowMinigameEndUI
// (BlueprintCallable, BlueprintEvent)

void UScoreboard_UI_C::ShowMinigameEndUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "ShowMinigameEndUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Scoreboard_UI.Scoreboard_UI_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScoreboard_UI_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "Tick");

	Params::Scoreboard_UI_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Scoreboard_UI.Scoreboard_UI_C.OnDisplayMinigameStartUI
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bDisplay                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UScoreboard_UI_C::OnDisplayMinigameStartUI(bool bDisplay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "OnDisplayMinigameStartUI");

	Params::Scoreboard_UI_C_OnDisplayMinigameStartUI Parms{};

	Parms.bDisplay = bDisplay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Scoreboard_UI.Scoreboard_UI_C.OnDisplayMinigameEndUI
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bDisplay                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UScoreboard_UI_C::OnDisplayMinigameEndUI(bool bDisplay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "OnDisplayMinigameEndUI");

	Params::Scoreboard_UI_C_OnDisplayMinigameEndUI Parms{};

	Parms.bDisplay = bDisplay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Scoreboard_UI.Scoreboard_UI_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UScoreboard_UI_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Scoreboard_UI.Scoreboard_UI_C.UpdateStats
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UScoreboard_UI_C::UpdateStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "UpdateStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Scoreboard_UI.Scoreboard_UI_C.GetScoreboardStateNames
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class FText>*                    OutNames                                               (Parm, OutParm, ZeroConstructor)

void UScoreboard_UI_C::GetScoreboardStateNames(TArray<class FText>* OutNames)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "GetScoreboardStateNames");

	Params::Scoreboard_UI_C_GetScoreboardStateNames Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutNames != nullptr)
		*OutNames = std::move(Parms.OutNames);
}


// Function Scoreboard_UI.Scoreboard_UI_C.UpdateScrollBasedOnTime
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Delta                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ScrollLength                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UScoreboard_UI_C::UpdateScrollBasedOnTime(float Delta, float ScrollLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Scoreboard_UI_C", "UpdateScrollBasedOnTime");

	Params::Scoreboard_UI_C_UpdateScrollBasedOnTime Parms{};

	Parms.Delta = Delta;
	Parms.ScrollLength = ScrollLength;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
