#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_M249_Skeleton_Dynamic_AnimBP

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SK_M249_Skeleton_Dynamic_AnimBP.SK_M249_Skeleton_Dynamic_AnimBP_C.ExecuteUbergraph_SK_M249_Skeleton_Dynamic_AnimBP
// 0x0004 (0x0004 - 0x0000)
struct SK_M249_Skeleton_Dynamic_AnimBP_C_ExecuteUbergraph_SK_M249_Skeleton_Dynamic_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SK_M249_Skeleton_Dynamic_AnimBP_C_ExecuteUbergraph_SK_M249_Skeleton_Dynamic_AnimBP;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
