#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SmasherStrength01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SmasherStrength01.SmasherStrength01_C
// 0x0000 (0x0068 - 0x0068)
class USmasherStrength01_C final : public UFortNavAreaAutomatic
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SmasherStrength01_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SmasherStrength01_C")
	}
	static class USmasherStrength01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USmasherStrength01_C>();
	}
};
DUMPER7_ASSERTS_USmasherStrength01_C;

SDK_NAMESPACE_END
