#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: STW_PlayerCameraModeBase

#include "Basic.hpp"

#include "STW_PlayerCameraModeMelee_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass STW_PlayerCameraModeBase.STW_PlayerCameraModeBase_C
// 0x0000 (0x0C50 - 0x0C50)
class USTW_PlayerCameraModeBase_C final : public USTW_PlayerCameraModeMelee_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("STW_PlayerCameraModeBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"STW_PlayerCameraModeBase_C")
	}
	static class USTW_PlayerCameraModeBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USTW_PlayerCameraModeBase_C>();
	}
};
DUMPER7_ASSERTS_USTW_PlayerCameraModeBase_C;

SDK_NAMESPACE_END
