#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SurvivorBadgeTypes

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum SurvivorBadgeTypes.SurvivorBadgeTypes
// NumValues: 0x0004
enum class ESurvivorBadgeTypes : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	SurvivorBadgeTypes_MAX                   = 3,
};

SDK_NAMESPACE_END
